# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5226f505c79eed74f2d95bd17e7338e26d43e5eed1aef478996baf202aff9d440a5636174cf19d669837a31f960d067c8153ad2968fb59da0dd4ab307784ca5

test:
  secret_key_base: bc33fff4889481ea86ca54f041b3c176d186513042520d71984843fd2f4418b3827b3cf2d898f8f991cd4e0b3a72c7c685f18c97712f4244b6c827413abdc275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
